services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: zora
      POSTGRES_PASSWORD: zora
      POSTGRES_DB: zora
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
